### ISSUE TITLE
UASP No longer getting right versions

### ISSUE THREAD

**Issue by P4R4NORM4L** [kennethrisa/uasp#4]
This is probably due to the fact that Umod has modifier their website

**Comment by kennethrisa** [comment]
What is not working? i testet a few plugins, that has an old version, and it also updated the the new version.

Can you send me the plugin that you having issue with?

**Comment by P4R4NORM4L** [comment]
I have fixed it by deleting the plugins JSON file and restarting. It's just stating the old versions even though they were updated to the new versions
